# version: '3.8'


# services:
#   server:
#     build:
#       context: ./backend
#     ports:
#       - "5000:5000"
#     environment:
#       - DB_HOST=mysql
#       - DB_USER=root
#       - DB_PASSWORD=root
#       - DB_NAME=book_schema
#     depends_on:
#       - mysql

#   client:
#     build:
#       context: ./client
#     ports:
#       - "3000:80"

#   mysql:
#     image: mysql:8
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: book_schema
#     ports:
#       - "3307:3306"
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:


version: '3.8'

services:
  server:
    build:
      context: ./backend
    ports:
      - "8800:8800"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=book_schema
    depends_on:
      - mysql

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_schema
    ports:
      # - "3307:3306"
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
